function dX = bislip_eom(X, u, params)
% Automatically generated by generate_bislip_eom.m

mb = params(1); Ib = params(2);
mf = params(3); ks = params(4); bs = params(5);
Ilm = params(6); blm = params(7);
Iam = params(8); bam = params(9); n = params(10);
g = params(11);
xb = X(1); dxb = X(2); yb = X(3); dyb = X(4); thb = X(5); dthb = X(6);
leqa = X(7); dleqa = X(8); la = X(9); dla = X(10); thoa = X(11); dthoa = X(12);
leqb = X(13); dleqb = X(14); lb = X(15); dlb = X(16); thob = X(17); dthob = X(18);
ldirxa = sin(thb + thoa); ldirya = -cos(thb + thoa);
ldirxb = sin(thb + thob); ldiryb = -cos(thb + thob);
Fla = u(1); Tma = u(2); Flb = u(3); Tmb = u(4);
Fbx = u(5); Fby = u(6); Tb = u(7);
Fefxa = u(8); Fefya = u(9); Fefxb = u(10); Fefyb = u(11);

J = [[0, 0, Iam, 0, 0, Iam*n, 0, 0, 0, 1, 0];
     [mf, 0, -la*ldirya*mf, 0, ldirxa*mf, -la*ldirya*mf, 0, 0, 0, (ldirya*n)/la, 0];
     [0, mf, la*ldirxa*mf, 0, ldirya*mf, la*ldirxa*mf, 0, 0, 0, -(ldirxa*n)/la, 0];
     [0, 0, 0, Ilm, 0, 0, 0, 0, 0, 0, 0];
     [0, 0, Iam, 0, 0, 0, 0, 0, Iam*n, 0, 1];
     [mf, 0, -lb*ldiryb*mf, 0, 0, 0, 0, ldirxb*mf, -lb*ldiryb*mf, 0, (ldiryb*n)/lb];
     [0, mf, lb*ldirxb*mf, 0, 0, 0, 0, ldiryb*mf, lb*ldirxb*mf, 0, -(ldirxb*n)/lb];
     [0, 0, 0, 0, 0, 0, Ilm, 0, 0, 0, 0];
     [0, 0, Ib, 0, 0, 0, 0, 0, 0, n - 1, n - 1];
     [mb, 0, 0, 0, 0, 0, 0, 0, 0, -(ldirya*n)/la, -(ldiryb*n)/lb];
     [0, mb, 0, 0, 0, 0, 0, 0, 0, (ldirxa*n)/la, (ldirxb*n)/lb]];

f0 = [[bam*dthoa*n - Tma];
      [ldirxa*(bs*(la - leqa) + ks*(la - leqa)) - mf*(2*dla*ldirya*(dthb + dthoa) + la*ldirxa*(dthb + dthoa)^2) - Fefxa];
      [g*mf - Fefya + mf*(2*dla*ldirxa*(dthb + dthoa) - la*ldirya*(dthb + dthoa)^2) + ldirya*(bs*(la - leqa) + ks*(la - leqa))];
      [blm*dleqa - Fla - bs*(la - leqa) - ks*(la - leqa)];
      [bam*dthob*n - Tmb];
      [ldirxb*(bs*(lb - leqb) + ks*(lb - leqb)) - mf*(2*dlb*ldiryb*(dthb + dthob) + lb*ldirxb*(dthb + dthob)^2) - Fefxb];
      [g*mf - Fefyb + mf*(2*dlb*ldirxb*(dthb + dthob) - lb*ldiryb*(dthb + dthob)^2) + ldiryb*(bs*(lb - leqb) + ks*(lb - leqb))];
      [blm*dleqb - Flb - bs*(lb - leqb) - ks*(lb - leqb)];
      [Tma - Tb + Tmb - bam*dthoa*n - bam*dthob*n];
      [- Fbx - ldirxa*(bs*(la - leqa) + ks*(la - leqa)) - ldirxb*(bs*(lb - leqb) + ks*(lb - leqb))];
      [g*mb - Fby - ldirya*(bs*(la - leqa) + ks*(la - leqa)) - ldiryb*(bs*(lb - leqb) + ks*(lb - leqb))]];

v = J\-f0;
tmp = [X(2:2:end)'; v(1:9)'];
dX = tmp(:);
